apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: go-jszqrser-gitops
  description: This is GitOps manifest for go-jszqrser   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=go-jszqrser
    backstage.io/kubernetes-id: go-jszqrser 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: chetna14manku-org/go-jszqrser-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:go-jszqrser
